### ISSUE TITLE
Publish update for SMAPI 1.9

### ISSUE THREAD

**Issue by Pathoschild** [thakyZ/zDailyIncrease#2]
PR #1 updated zDailyIncrease for SMAPI 1.9, but the update isn't available for players yet. Can you publish a mod package to the [releases page](https://github.com/thakyZ/zDailyIncrease/releases) and [mod page](http://community.playstarbound.com/resources/smapi-zdailyincrease.4247/)? Here's a compiled version you can upload if it helps:
* [zDailyIncrease 1.3.3.zip](https://github.com/thakyZ/zDailyIncrease/files/930394/zDailyIncrease-1.3.3.zip)

**Comment by thakyZ** [comment]
EHHHHHHHAAAAA!!! I will get on it right now, I totally forgot. I was at work when I committed and the like.

**Comment by thakyZ** [comment]
OK, all is good! I have posted the updates and will close this issue now.
